CREATE TABLE job_application (
                                 id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 company_name VARCHAR(150) NOT NULL,
                                 role_title   VARCHAR(150) NOT NULL,
                                 source       VARCHAR(100),
                                 status       VARCHAR(20)  NOT NULL,
                                 applied_on   DATE         NOT NULL,
                                 notes        TEXT
);

CREATE INDEX idx_job_application_status ON job_application (status);