CREATE TABLE interview (
                                id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                scheduled_at TIMESTAMP NOT NULL,
                                type VARCHAR(20) NOT NULL,
                                result VARCHAR(20) NOT NULL,
                                application_id BIGINT NOT NULL,
                                CONSTRAINT fk_interview_application
                                    FOREIGN KEY (application_id) REFERENCES job_application(id)
                                    ON DELETE CASCADE

);

CREATE INDEX idx_interview_application_id ON interview (application_id);